const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');

const args = process.argv.slice(2);
let OUT = path.join(__dirname, 'compiled.luau');
for (let i = 0; i < args.length; i++) {
    if (args[i] === '--out') OUT = path.resolve(process.cwd(), args[i + 1]);
}

const TEXT_EXTENSIONS = new Set(['.luau', '.lua', '.json', '.txt']);
const BINARY_EXTENSIONS = new Set(['.png']);
const SKIP_DIRS = new Set(['.git', 'node_modules', '.qodo', 'Compilation']);

function walk(dir, root, entries, isRoot) {
    if (SKIP_DIRS.has(path.basename(dir))) return;
    const items = fs.readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name));
    for (const item of items) {
        const full = path.join(dir, item.name);
        const rel = path.relative(root, full).split(path.sep).join('/');
        if (item.isDirectory()) {
            walk(full, root, entries, false);
        } else {
            if (isRoot && item.name !== 'client.luau') continue;
            const ext = path.extname(item.name).toLowerCase();
            if (TEXT_EXTENSIONS.has(ext) || BINARY_EXTENSIONS.has(ext)) {
                entries.push({ rel, full, ext });
            }
        }
    }
}

const entries = [];
walk(ROOT, ROOT, entries, true);
entries.sort((a, b) => a.rel.localeCompare(b.rel));

function luaStringEscape(buf) {
    const bin = buf.toString('latin1');
    let out = '"';
    for (let i = 0; i < bin.length; i++) {
        const c = bin.charCodeAt(i);
        const ch = bin[i];
        if (ch === '\\') out += '\\\\';
        else if (ch === '"') out += '\\"';
        else if (ch === '\n') out += '\\n';
        else if (ch === '\r') out += '\\r';
        else if (ch === '\t') out += '\\t';
        else if (c < 32 || c > 126) out += '\\' + String(c).padStart(3, '0');
        else out += ch;
    }
    out += '"';
    return out;
}

const B64_DECODER = `
getgenv().NEXS_B64DECODE = function(data)
    local b64chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
    local lookup = {}
    for i = 1, 64 do lookup[b64chars:sub(i, i)] = i - 1 end
    local out = {}
    local bits = 0
    local value = 0
    for i = 1, #data do
        local c = data:sub(i, i)
        if c == "=" then break end
        local n = lookup[c]
        if n then
            value = value * 64 + n
            bits = bits + 6
            if bits >= 8 then
                bits = bits - 8
                out[#out + 1] = string.char(math.floor(value / 2 ^ bits) % 256)
                value = value % 2 ^ bits
            end
        end
    end
    return table.concat(out)
end
`;

const header = [
    '--[[',
    '  Hub4V - Compiled single-file build',
    '  Generated by Compilation/Compilation.js at ' + new Date().toISOString(),
    '  Bundled ' + entries.length + ' files (client.luau + src/ + Script/ + Assets/).',
    ']]',
    '',
    'getgenv().NEXS_PACKAGE = getgenv().NEXS_PACKAGE or {}',
    '',
].join('\n');

const body = [];
for (const e of entries) {
    const buf = fs.readFileSync(e.full);
    let literal;
    if (e.ext === '.png') {
        literal = luaStringEscape(Buffer.from(buf.toString('base64'), 'latin1'));
    } else {
        literal = luaStringEscape(buf);
    }
    const key = luaStringEscape(Buffer.from(e.rel, 'latin1'));
    body.push(`getgenv().NEXS_PACKAGE[${key}] = ${literal}`);
}

let output = header;
output += '-- base64 decoder used for embedded .png assets\n';
output += B64_DECODER.trim() + '\n\n';
output += '-- embedded project files\n';
output += body.join('\n') + '\n\n';
output += '-- boot the client (reads everything from the package, no extra requests)\n';
output += 'loadstring(getgenv().NEXS_PACKAGE["client.luau"])()\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, output);

let totalBytes = 0;
for (const e of entries) totalBytes += fs.statSync(e.full).size;
console.log(`Compiled ${entries.length} files (${(totalBytes / 1024).toFixed(1)} KiB source)`);
console.log(`Output: ${OUT} (${(Buffer.byteLength(output) / 1024).toFixed(1)} KiB)`);